### PR TITLE
Team members ui

### LINKED ISSUE #28: Create the UI for list of users for admin
Acceptance Criteria 
- just develop the UI for the that will be a list of users , under the admin 
- add option to remove from db

### PR DESCRIPTION
**Pull request by rpasricha45**
Created UI for members 
the routing integration has not been set up yet for the component just the UI , under members.js

### CODE REVIEW

**Review by ammist07 — APPROVED** [review]
Looks Good

**Comment by brandonRodriguez24** [comment]
looks great

**Review by brandonRodriguez24 — COMMENTED** [review]
thumbs up emoji*

**Comment by rpasricha45** [comment]
I'm not sure why there are 32 files changed , showing , I just updated from main , from the branch , before this branch had old testing file , which caused the test to fail.  It looks like it has the other commits that we had in the main branch , there are not conflicts like before or any errors with the test

**Pull request merged**
